version: '3'
services:
  bigstream:
    image: "${BIGSTREAM_IMG}"
    container_name: bs_bigstream
    restart: always
    networks:
     - bsnet
    ports:
     - "${PREFIX_NO}980:19980"
     - "${PREFIX_NO}080:19080"
     - "${PREFIX_NO}180:19180"
    environment:
     - "BS_SECRET=${BS_SECRET}"
    volumes:
     - bsdata:/var/bigstream/data
  redis:
    image: "redis:${REDIS_TAG}"
    command: redis-server --appendonly yes
    container_name: bs_redis_server
    restart: always
    networks:
       bsnet:
          aliases:
             - redis-server
    volumes:
     - bsredis:/data
  rabbitmq:
    image: "${RABBITMQ_IMG}"
    command: rabbitmq-server --hostname rabbitmq-server
    container_name: bs_rabbitmq_server
    restart: always
    networks:
       bsnet:
          aliases:
             - rabbitmq-server
volumes:
  bsdata:
  bsredis:
networks:
  bsnet:
     driver: bridge